### ISSUE TITLE
Open shared drive "data" folder

### ISSUE THREAD

**Issue by nikita-p** [82492749123082/farich-pics#21]
Идея в том, что с открытой папкой "data" будет намного проще передавать ссылки для быстрого скачивания файлов для colab easy run  (но это может сделать только админ диска)

Для закрытых данных можно организовать доп. директорию на общем диске

Что думаешь?

**Comment by nikita-p** [comment]
@savchenkoyana, ты вроде не можешь этого сделать -> закрываю issue?

**Comment by savchenkoyana** [comment]
Закрываем
