### ISSUE TITLE
Написать документацию для новой версии кода и добавить на https://82492749123082.github.io/farich-pics/

### ISSUE THREAD

**Issue by savchenkoyana** [82492749123082/farich-pics#35]
Писать документацию в `page/wiki`

Документация к:
- [x] `BoardsGenerator`
- [x] `Augmentator`

**Comment by nikita-p** [comment]
* Написал док к классу [`BoardsGenerator`](https://github.com/82492749123082/farich-pics/blob/dev/page/wiki/BoardsGenerator.md)
* Док к классу [`Augmentator`](https://github.com/82492749123082/farich-pics/blob/dev/page/wiki/Augmentator.md)
* Поправил **Readme.MD**

**Comment by savchenkoyana** [comment]
@nikita-p , а вытаскивать все это сюда https://82492749123082.github.io/farich-pics/ не будешь?

**Comment by nikita-p** [comment]
Буду, но это сделаю в финальной версии, когда в `master` будем v1.0 заливать
Потому что сейчас ещё всё может измениться, а `master` у нас для окончательных вариантов
