### ISSUE TITLE
Написать ML способ отделения сигнала/шума

### ISSUE THREAD

**Issue by nikita-p** [82492749123082/farich-pics#43]

**Comment by savchenkoyana** [comment]
Ты же вроде бы сделал, @nikita-p , закрываем?

**Comment by nikita-p** [comment]
файл пока не в репозитории, так что пусть останется in progress

**Comment by nikita-p** [comment]
https://colab.research.google.com/drive/1ljftwmqe19-c-599EU9eDCdjy6fRLjiJ?usp=sharing
